### ISSUE TITLE
LICENCE

### ISSUE THREAD

**Issue by zitterbewegung** [fulldecent/erc721-example#1]
What license is this under?

**Comment by fulldecent** [comment]
Updated with 920b166ea2de874b736d9779bcbb2330e6213096

Presently this is All Rights Reserved with a commitment to change to MIT license in the future.

I apologize if this is not the answer you hoped for or if there was any confusion on this matter before you started involving with this project.

**Comment by fulldecent** [comment]
And thank you for the question.

**Comment by zitterbewegung** [comment]
No problem ! Thank you for the update .
